#!/usr/bin/expect -f
set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 30
match_max 100000
spawn /usr/sbin/dpkg-reconfigure ca-certificates
expect "ca-certificates configuration"
send -- "	"
expect -exact "\[37m\[45myes  \[23;38H\[41m<Ok>\[23;39H"
send -- "\r"
expect "<Ok>"
send -- "	"
expect -exact "\[12;4H\[37m\[45m*\[28;38H\[41m<Ok>\[28;39H"
send -- "\r"
expect "done."
sleep 1
