#!/usr/bin/expect -f
set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 30
match_max 100000
spawn /usr/sbin/dpkg-reconfigure ca-certificates
expect "ca-certificates configuration"
send -- "\t"
expect "<Ok>"
send -- "\r"
expect "<Ok>"
send -- "\t"
expect "<Ok>"
send -- "\r"
expect "done."
sleep 1
